# Generated by Django 5.0.4 on 2024-04-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_degree_options_alter_studyingarea_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Екзамен', 'verbose_name_plural': 'Екзамени'},
        ),
        migrations.AddField(
            model_name='exam',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='main.studyingarea', verbose_name='На спеціальінсть'),
            preserve_default=False,
        ),
    ]
