# Generated by Django 5.0.4 on 2024-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_exam_options_exam_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='form',
        ),
        migrations.AlterField(
            model_name='exam',
            name='audience',
            field=models.CharField(default=320, max_length=50, verbose_name='Номер аудиторії'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ЄВІ'), (2, 'Фаховий іспит')], verbose_name='Тип екзамену'),
        ),
    ]
